name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Установка зависимостей
        run: npm ci

  test:
    runs-on: windows-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Установка зависимостей
        run: npm ci

      - name: Запуск тестов
        run: npm run test

  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2

      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Установка зависимостей
        run: npm ci

      - name: Деплой приложения
        run: npm run deploy
